package google

import (
	"cloud.google.com/go/pubsub"
	"context"
	"errors"
	"github.com/quantumcycle/expedit/core/message"
	"github.com/quantumcycle/expedit/core/publisher"
	"time"
)

var DefaultPublishTimeout = 60 * time.Second

type OrderingKeyProvider func(message *message.Message) string

type AttributesProvider func(message *message.Message) map[string]string

func MetadataAsAttributes(msg *message.Message) map[string]string {
	return msg.Metadata
}

type PublisherOption func(*PublisherOptions)

type PublisherOptions struct {
	orderingKeyProvider OrderingKeyProvider
	attributesProvider  AttributesProvider
	publishTimeout      time.Duration
}

// WithOrderingKeyProvider is a function that returns an ordering key for a given message. If not provided, no ordering key is used.
func WithOrderingKeyProvider(provider OrderingKeyProvider) PublisherOption {
	return func(opts *PublisherOptions) {
		opts.orderingKeyProvider = provider
	}
}

// WithAttributesProvider is a function that returns attributes for a given message. If not provided, no attributes are used.
// A provider to set the attribute on the pubsub message.
// By default, it's using MetadataAsAttributes which converts all metadata entries as attributes.
func WithAttributesProvider(provider AttributesProvider) PublisherOption {
	return func(opts *PublisherOptions) {
		opts.attributesProvider = provider
	}
}

// WithPublishTimeout is a timeout for publishing a message. DefaultPublishTimeout is used if not provided.
func WithPublishTimeout(timeout time.Duration) PublisherOption {
	return func(opts *PublisherOptions) {
		opts.publishTimeout = timeout
	}
}

type Publisher struct {
	internalPublisher *publisher.MessagePublisher[*pubsub.Message]
}

type PubsubTopic struct {
	topic *pubsub.Topic
}

func (p PubsubTopic) Close() error {
	p.topic.Stop()
	return nil
}

func (p PubsubTopic) Publish(ctx context.Context, message *pubsub.Message) error {
	//ID is readonly so it must not be set to avoid errors
	if message.ID != "" {
		return errors.New("message ID is readonly with the google publisher implementation. ID is generated by the server")
	}

	r := p.topic.Publish(ctx, message)
	serverID, err := r.Get(ctx)
	if err != nil {
		return err
	}
	message.ID = serverID
	return nil
}

func (p PubsubTopic) GetMessageID(message *pubsub.Message) string {
	if message == nil {
		return ""
	}
	return message.ID
}

func NewGooglePublisher(
	c *pubsub.Client,
	routingFunc publisher.RoutingFunc,
	opts ...PublisherOption) (*Publisher, error) {
	if c == nil {
		return nil, errors.New("client is required")
	}
	if routingFunc == nil {
		return nil, errors.New("routing function is required")
	}

	options := PublisherOptions{
		publishTimeout:     DefaultPublishTimeout,
		attributesProvider: MetadataAsAttributes,
	}
	for _, opt := range opts {
		opt(&options)
	}

	internalPublisher := &publisher.MessagePublisher[*pubsub.Message]{
		RoutingFunc: routingFunc,
		MessageMarshaller: func(msg *message.Message) (*pubsub.Message, error) {
			if _, ok := msg.Payload.([]byte); !ok {
				return nil, errors.New("payload must be []byte. Use a middleware to convert the payload to []byte")
			}
			msgImpl := &pubsub.Message{
				ID:   msg.ID,
				Data: msg.Payload.([]byte),
			}
			if options.orderingKeyProvider != nil {
				msgImpl.OrderingKey = options.orderingKeyProvider(msg)
			}
			if options.attributesProvider != nil {
				msgImpl.Attributes = options.attributesProvider(msg)
			}
			return msgImpl, nil
		},
		PublishTimeout: options.publishTimeout,
		GetDestinationPublisher: func(dest publisher.Destination) (publisher.MessagesPublisherImpl[*pubsub.Message], error) {
			pubTopic := c.Topic(string(dest))
			if options.orderingKeyProvider != nil {
				pubTopic.EnableMessageOrdering = true
			}
			return PubsubTopic{
				topic: pubTopic,
			}, nil
		},
	}

	p := &Publisher{
		internalPublisher: internalPublisher,
	}
	return p, nil
}

func (p *Publisher) Publish(message *message.Message) error {
	return p.internalPublisher.Publish(message)
}

func (p *Publisher) Close() error {
	return p.internalPublisher.Close()
}
