## Original source: https://github.com/marcelcorso/gcloud-pubsub-emulator/blob/master/Dockerfile
FROM golang:alpine as builder

RUN apk update && apk upgrade && apk add --no-cache curl git

RUN curl -s https://raw.githubusercontent.com/eficode/wait-for/master/wait-for -o /usr/bin/wait-for
RUN chmod +x /usr/bin/wait-for

RUN go install github.com/prep/pubsubc@latest

###############################################################################

FROM google/cloud-sdk:443.0.0-alpine

RUN apk --update add openjdk8-jre netcat-openbsd && gcloud components install beta pubsub-emulator

COPY --from=builder /usr/bin/wait-for /usr/bin
COPY --from=builder /go/bin/pubsubc   /usr/bin
COPY                run.sh            /run.sh

EXPOSE 8585

CMD /run.sh
